
## the index folder for STAR, change to mm9 if it is mouse
bowtie2_index: "/work/06032/tg853315/stampede2/genome_index/mm10_bt2/Bowtie2Index/genome"
## gtf file for annotation

Genrich: "/work/06032/tg853315/stampede2/software/bin/Genrich"
## hisat location

bbbuk: '/work/06032/tg853315/stampede2/software/bbmap/bbduk.sh'
adaptors: '/work/06032/tg853315/stampede2/software/bbmap/resources/adapters.fa'
## use which program to count 

# Path to a JSON file with samples and their corresponding FASTQ files.
SAMPLES_JSON: './samples.json'

#CLUSTER_JSON: './cluster.json'
